# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 11:25
from __future__ import unicode_literals

import contrib.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import itfsite.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(db_index=True, help_text='The date & time the action actually ocurred in the real world.')),
                ('outcome', models.IntegerField(blank=True, help_text="The outcome index that was taken. May be null if the Actor should have participated but didn't (we want to record to avoid counterintuitive missing data).", null=True)),
                ('name_long', models.CharField(help_text="The long form of the person's name at the time of the action, meant for a page title.", max_length=128)),
                ('name_short', models.CharField(help_text="The short form of the person's name at the time of the action, usually a last name, meant for in-page second references.", max_length=128)),
                ('name_sort', models.CharField(help_text="The sorted list form of the person's name at the time of the action.", max_length=128)),
                ('party', enumfields.fields.EnumIntegerField(enum=contrib.models.ActorParty, help_text='The party of the Actor at the time of the action.')),
                ('title', models.CharField(help_text='Descriptive text for the office held by this actor at the time of the action.', max_length=200)),
                ('office', models.CharField(blank=True, help_text='A code specifying the office held by the Actor at the time the Action was created, in the same format as Recipient.office_sought.', max_length=7, null=True)),
                ('extra', itfsite.utils.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('total_contributions_for', models.DecimalField(decimal_places=2, default=0, help_text='A cached total amount of campaign contributions executed with the actor as the recipient (excluding fees).', max_digits=6)),
                ('total_contributions_against', models.DecimalField(decimal_places=2, default=0, help_text='A cached total amount of campaign contributions executed with an opponent of the actor as the recipient (excluding fees).', max_digits=6)),
                ('reason_for_no_outcome', models.CharField(blank=True, help_text="If outcome is null, why. E.g. 'Did not vote.'.", max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govtrack_id', models.IntegerField(help_text="GovTrack's ID for this person.", unique=True)),
                ('votervoice_id', models.IntegerField(blank=True, help_text="VoterVoice's target ID for this person.", null=True, unique=True)),
                ('office', models.CharField(blank=True, help_text='A code specifying the office currently held by the Actor, in the same format as Recipient.office_sought.', max_length=7, null=True, unique=True)),
                ('name_long', models.CharField(help_text="The long form of the person's current name, meant for a page title.", max_length=128)),
                ('name_short', models.CharField(help_text="The short form of the person's current name, usually a last name, meant for in-page second references.", max_length=128)),
                ('name_sort', models.CharField(help_text="The sorted list form of the person's current name.", max_length=128)),
                ('party', enumfields.fields.EnumIntegerField(enum=contrib.models.ActorParty, help_text='The current party of the Actor. For Members of Congress, this is based on how the Member caucuses to avoid Independent as much as possible.')),
                ('title', models.CharField(help_text='Descriptive text for the office held by this actor.', max_length=200)),
                ('extra', itfsite.utils.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('inactive_reason', models.CharField(blank=True, help_text="If the Actor is still a public official (i.e. generates Actions) but should not get contributions, the reason why. If not None, serves as a flag. E.g. 'Not running for reelection.'.", max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CancelledPledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pledge', itfsite.utils.JSONField(blank=True, help_text='The original Pledge information.')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', enumfields.fields.EnumIntegerField(default=0, enum=contrib.models.ContributionRecipientType, help_text='The logical specification of the recipient, i.e. the Actor (incumbent) or a general election challenger of the Actor.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of the contribution, in dollars.', max_digits=6)),
                ('refunded_time', models.DateTimeField(blank=True, help_text='If the contribution was refunded to the user, the time that happened.', null=True)),
                ('de_id', models.CharField(help_text='The Democracy Engine ID that the contribution was assigned to.', max_length=64)),
                ('extra', itfsite.utils.JSONField(blank=True, help_text='Additional information about the contribution.')),
            ],
        ),
        migrations.CreateModel(
            name='ContributorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cclastfour', models.CharField(blank=True, db_index=True, help_text="The last four digits of the user's credit card number, stored & indexed for fast look-up in case we need to find a pledge from a credit card number.", max_length=4, null=True)),
                ('is_geocoded', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been geocoded.')),
                ('extra', itfsite.utils.JSONField(blank=True, help_text='Schemaless data stored with this object.')),
            ],
        ),
        migrations.CreateModel(
            name='IncompletePledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('email', models.EmailField(db_index=True, help_text='An email address.', max_length=254, unique=True)),
                ('extra', itfsite.utils.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('sent_followup_at', models.DateTimeField(blank=True, db_index=True, help_text="If we've sent a follow-up email, the date and time we sent it.", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, db_index=True, help_text='An optional referral code that lead the user to take this action.', max_length=24, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('algorithm', models.IntegerField(default=0, help_text='In case we change our terms & conditions, or our explanation of how things work, an integer indicating the terms and expectations at the time the user made the pledge.')),
                ('status', enumfields.fields.EnumIntegerField(default=1, enum=contrib.models.PledgeStatus, help_text='The current status of the pledge.')),
                ('made_after_trigger_execution', models.BooleanField(default=False, help_text='Whether this Pledge was created after the Trigger was executed (i.e. outcomes known).')),
                ('desired_outcome', models.IntegerField(help_text='The outcome index that the user desires.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The pledge amount in dollars (including fees). The credit card charge may be less in the event that we have to round to the nearest penny-donation.', max_digits=6)),
                ('incumb_challgr', models.FloatField(help_text='A float indicating how to split the pledge: -1 (to challenger only) <=> 0 (evenly split between incumbends and challengers) <=> +1 (to incumbents only)')),
                ('filter_party', enumfields.fields.EnumIntegerField(blank=True, enum=contrib.models.ActorParty, help_text='Contributions only go to candidates whose party matches this party. Independent is not an allowed value here.', null=True)),
                ('filter_competitive', models.BooleanField(default=False, help_text='Whether to filter contributions to competitive races.')),
                ('tip_to_campaign_owner', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The amount in dollars that the user desires to send to the owner of via_campaign, zero if there is no one to tip or the user desires not to tip.', max_digits=6)),
                ('cclastfour', models.CharField(blank=True, db_index=True, help_text="The last four digits of the user's credit card number, stored & indexed for fast look-up in case we need to find a pledge from a credit card number.", max_length=4, null=True)),
                ('email_confirmed_at', models.DateTimeField(blank=True, help_text='The date and time that the email address of the pledge became confirmed, if the pledge was originally based on an unconfirmed email address.', null=True)),
                ('pre_execution_email_sent_at', models.DateTimeField(blank=True, help_text='The date and time when the user was sent an email letting them know that their pledge is about to be executed.', null=True)),
                ('post_execution_email_sent_at', models.DateTimeField(blank=True, help_text='The date and time when the user was sent an email letting them know that their pledge was executed.', null=True)),
                ('extra', itfsite.utils.JSONField(blank=True, help_text='Additional information stored with this object.')),
            ],
        ),
        migrations.CreateModel(
            name='PledgeExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('problem', enumfields.fields.EnumIntegerField(default=0, enum=contrib.models.PledgeExecutionProblem, help_text='A problem code associated with a failure to make any contributions for the pledge.')),
                ('charged', models.DecimalField(decimal_places=2, help_text="The amount the user's account was actually charged, in dollars and including fees. It may differ from the pledge amount to ensure that contributions of whole-cent amounts could be made to candidates.", max_digits=6)),
                ('fees', models.DecimalField(decimal_places=2, help_text='The fees the user was charged, in dollars.', max_digits=6)),
                ('extra', itfsite.utils.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('district', models.CharField(blank=True, db_index=True, help_text='The congressional district of the user (at the time of the pledge), in the form of XX00.', max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_id', models.CharField(help_text='The Democracy Engine ID that we have assigned to this recipient.', max_length=64, unique=True)),
                ('active', models.BooleanField(default=True, help_text='Whether this Recipient can currently receive funds.')),
                ('office_sought', models.CharField(blank=True, db_index=True, help_text="For challengers, a code specifying the office sought in the form of 'S-NY-I' (New York class 1 senate seat) or 'H-TX-30' (Texas 30th congressional district). Unique with party.", max_length=7, null=True)),
                ('party', enumfields.fields.EnumIntegerField(blank=True, enum=contrib.models.ActorParty, help_text='The party of the challenger, or null if this Recipient is for an incumbent. Unique with office_sought.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of the tip, in dollars.', max_digits=6)),
                ('de_recip_id', models.CharField(blank=True, db_index=True, help_text='The recipient ID on Democracy Engine that received the tip.', max_length=64, null=True)),
                ('ref_code', models.CharField(blank=True, db_index=True, help_text='An optional referral code that lead the user to take this action.', max_length=24, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('extra', itfsite.utils.JSONField(blank=True, help_text='Additional information stored with this object.')),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, db_index=True, help_text='An opaque look-up key to quickly locate this object.', max_length=64, null=True, unique=True)),
                ('title', models.CharField(help_text='The legislative action that this trigger is about, in wonky language.', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('description', models.TextField(help_text='Describe what event will cause contributions to be made. Use the second person and future tense, e.g. by starting with "Your contribution will...". The text is in the format given by description_format.')),
                ('description_format', enumfields.fields.EnumIntegerField(default=1, enum=itfsite.utils.TextFormat, help_text='The format of the description text.')),
                ('status', enumfields.fields.EnumIntegerField(default=0, enum=contrib.models.TriggerStatus, help_text='The current status of the trigger: Open (accepting pledges), Paused (not accepting pledges), Executed (funds distributed), Vacated (existing pledges invalidated).')),
                ('outcomes', itfsite.utils.JSONField(default='[{"object": "in favor of the bill", "vote_key": "+", "label": "Yes on This Vote"}, {"object": "against passage of the bill", "vote_key": "-", "label": "No on This Vote"}]', help_text="An array (order matters!) of information for each possible outcome of the trigger, e.g. ['Voted Yes', 'Voted No'].")),
                ('extra', itfsite.utils.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('pledge_count', models.IntegerField(default=0, help_text='A cached count of the number of pledges made *prior* to trigger execution (excludes Pledges with made_after_trigger_execution).')),
                ('total_pledged', models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='A cached total amount of pledges made *prior* to trigger execution (excludes Pledges with made_after_trigger_execution).', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerCustomization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('outcome', models.IntegerField(blank=True, help_text='Restrict Pledges to this outcome.', null=True, verbose_name='Restrict Outcome')),
                ('incumb_challgr', models.FloatField(blank=True, help_text="Restrict Pledges to be for just incumbents, just challengers, both incumbents and challengers (where user can't pick), or don't restrict the user's choice.", null=True, verbose_name='Restrict Incumbent-Challenger Choice')),
                ('filter_party', enumfields.fields.EnumIntegerField(blank=True, enum=contrib.models.ActorParty, help_text='Restrict Pledges to be to candidates of this party.', null=True, verbose_name='Restrict Party')),
                ('filter_competitive', models.NullBooleanField(default=False, help_text='Restrict Pledges to this filter_competitive value.', verbose_name='Restrict Competitive Filter')),
                ('extra', itfsite.utils.JSONField(blank=True, help_text='Additional information stored with this object.')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('action_time', models.DateTimeField(help_text='The date & time the action actually ocurred in the real world.')),
                ('cycle', models.IntegerField(help_text='The election cycle (year) that the trigger was executed in.')),
                ('description', models.TextField(help_text='Describe how contriutions are being distributed. Use the passive voice and present progressive tense, e.g. by starting with "Contributions are being distributed...".')),
                ('description_format', enumfields.fields.EnumIntegerField(enum=itfsite.utils.TextFormat, help_text='The format of the description text.')),
                ('pledge_count', models.IntegerField(default=0, help_text='A cached count of the number of pledges executed. This counts pledges from anonymous users that do not result in contributions. Used to check when a Trigger is done executing.')),
                ('pledge_count_with_contribs', models.IntegerField(default=0, help_text='A cached count of the number of pledges executed with actual contributions made.')),
                ('num_contributions', models.IntegerField(db_index=True, default=0, help_text='A cached total number of campaign contributions executed.')),
                ('total_contributions', models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='A cached total amount of campaign contributions executed, excluding fees.', max_digits=6)),
                ('extra', itfsite.utils.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('trigger', models.OneToOneField(help_text='The Trigger this execution information is about.', on_delete=django.db.models.deletion.PROTECT, related_name='execution', to='contrib.Trigger')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symmetric', models.BooleanField(default=False, help_text='If true, the recommendation goes both ways.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notifications_created', models.BooleanField(db_index=True, default=False, help_text='Set to true once notifications have been generated for users for any past actions the users took before this recommendation was added.')),
                ('trigger1', models.ForeignKey(help_text='If a user has taken action on this Trigger, then we send them a notification.', on_delete=django.db.models.deletion.CASCADE, related_name='recommends', to='contrib.Trigger')),
                ('trigger2', models.ForeignKey(help_text='This is the trigger that we recommend the user take action on.', on_delete=django.db.models.deletion.CASCADE, related_name='recommended_by', to='contrib.Trigger')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerStatusUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(help_text='Status update text in the format given by text_format.')),
                ('text_format', enumfields.fields.EnumIntegerField(enum=itfsite.utils.TextFormat, help_text='The format of the text.')),
                ('trigger', models.ForeignKey(help_text='The Trigger that this update is about.', on_delete=django.db.models.deletion.CASCADE, to='contrib.Trigger')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, db_index=True, help_text='An opaque look-up key to quickly locate this object.', max_length=64, null=True, unique=True)),
                ('title', models.CharField(help_text='The title for the trigger.', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('strings', itfsite.utils.JSONField(default={}, help_text='A dictionary of displayable text.')),
                ('extra', itfsite.utils.JSONField(blank=True, help_text='Additional information stored with this object.')),
            ],
        ),
    ]
