# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 16:28
from __future__ import unicode_literals

import contrib.models
from django.db import migrations
import enum3field


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0002_auto_20160619_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='recipient_type',
            field=enum3field.EnumField(contrib.models.ContributionRecipientType, choices=[(contrib.models.ContributionRecipientType(0), 'Null'), (contrib.models.ContributionRecipientType(1), 'Incumbent'), (contrib.models.ContributionRecipientType(2), 'GeneralChallenger')], default=contrib.models.ContributionRecipientType(0), help_text='The logical specification of the recipient, i.e. the Actor (incumbent) or a general election challenger of the Actor.'),
        ),
    ]
