# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import itfsite.accounts
import itfsite.models
import itfsite.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrib', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Whether the user can log into this admin.')),
                ('is_active', models.BooleanField(default=True, help_text='Unselect this instead of deleting accounts.')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('notifs_freq', enumfields.fields.EnumIntegerField(default=1, enum=itfsite.accounts.NotificationsFrequency, help_text='Now often the user wants to get non-obligatory notifications.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': (('see_user_emails', 'Can see the email addresses of our users'),),
            },
        ),
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('sentConfirmationEmail', models.BooleanField(default=False, help_text='Have we sent this user an email to confirm their address and activate their account/actions?')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra', itfsite.utils.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('confirmed_user', models.ForeignKey(blank=True, help_text='The user that this record became confirmed as.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.IntegerField(choices=[(1, 'if.then.fund'), (2, 'progressive.fund'), (99, '279forchange.us')], default=1, help_text='Which multi-brand site does this campaign appear on.')),
                ('title', models.CharField(help_text='The title for the campaign.', max_length=200)),
                ('slug', models.SlugField(help_text='The URL slug for this campaign.', max_length=200)),
                ('subhead', models.TextField(help_text='Short sub-heading text for use in list pages and the meta description tag, in the format given by subhead_format.')),
                ('subhead_format', enumfields.fields.EnumIntegerField(default=1, enum=itfsite.utils.TextFormat, help_text='The format of the subhead and image_credit text.')),
                ('status', enumfields.fields.EnumIntegerField(default=0, enum=itfsite.models.CampaignStatus, help_text='The current status of the campaign.')),
                ('headline', models.CharField(help_text='Headline text for the page.', max_length=256)),
                ('og_image', models.ImageField(blank=True, help_text="The og:image (for Facebook and Twitter posts) for the campaign. At least 120px x 120px and must be square. If not set and the campaign has an owner, then the owner's og:image is used.", null=True, upload_to='campaign-media')),
                ('splash_image', models.ImageField(blank=True, help_text='The big image to display behind the main call to action. Should be about 1300px wide and at least 500px tall, but the image will be resized and cropped as necessary.', null=True, upload_to='campaign-media')),
                ('image_credit', models.TextField(blank=True, help_text='Image credit, in the same format as the subhead.', null=True)),
                ('body_text', models.TextField(help_text='Body text, in the format given by body_format.')),
                ('body_format', enumfields.fields.EnumIntegerField(default=1, enum=itfsite.utils.TextFormat, help_text='The format of the body_text field.')),
                ('extra', itfsite.utils.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('contrib_triggers', models.ManyToManyField(blank=True, help_text='Triggers to offer the user to take action on (or to show past actions).', related_name='campaigns', to='contrib.Trigger')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', enumfields.fields.EnumIntegerField(enum=itfsite.models.NotificationType, help_text='The type of the notiication.')),
                ('source_object_id', models.PositiveIntegerField(help_text='The primary key of the object generating the notiication.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('dismissed_at', models.DateTimeField(blank=True, help_text='Whether and when the notification was dismissed by the user by.', null=True)),
                ('mailed_at', models.DateTimeField(blank=True, help_text='Whether and when the notification was sent to the user by email.', null=True)),
                ('clicked_at', models.DateTimeField(blank=True, help_text='Whether and when the notification was clicked on by the user to see more information.', null=True)),
                ('extra', itfsite.utils.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('source_content_type', models.ForeignKey(help_text='The content type of the object generating the notiication.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(help_text='The user the notification is sent to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Organization.', max_length=200)),
                ('slug', models.SlugField(help_text='The unique URL slug for this Organization.', max_length=200)),
                ('orgtype', enumfields.fields.EnumIntegerField(enum=itfsite.models.OrganizationType, help_text='The type of the organization.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('description', models.TextField(help_text='Description text in the format given by description_format.')),
                ('description_format', enumfields.fields.EnumIntegerField(default=1, enum=itfsite.utils.TextFormat, help_text='The format of the description text.')),
                ('profile_image', models.ImageField(blank=True, help_text="The logo or headshot to display as the profile picture on the organization's page, and the default og:image (for Facebook and Twitter posts) if og_image is not provided. At least 120px x 120px and must be square.", null=True, upload_to='campaign-media')),
                ('og_image', models.ImageField(blank=True, help_text="The og:image (for Facebook and Twitter posts) for the organization's profile page and the default og:image for the organization's campaigns. At least 120px x 120px and must be square.", null=True, upload_to='campaign-media')),
                ('banner_image', models.ImageField(blank=True, help_text="This organization's banner image. Should be about 1300px wide and at least 500px tall, but the image will be resized and cropped as necessary.", null=True, upload_to='org-banner-image')),
                ('website_url', models.URLField(blank=True, help_text="The URL to this organization's website.", max_length=256, null=True)),
                ('facebook_url', models.URLField(blank=True, help_text="The URL to this organization's Facebook Page.", max_length=256, null=True)),
                ('twitter_handle', models.CharField(blank=True, help_text="The organization's Twitter handle (omit the @-sign).", max_length=64, null=True)),
                ('de_recip_id', models.CharField(blank=True, help_text='The recipient ID on Democracy Engine for taking tips.', max_length=64, null=True)),
                ('extra', itfsite.utils.JSONField(blank=True, help_text='Additional information stored with this object.')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user/organization which owns the campaign. Null if the campaign is created by us.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='itfsite.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set([('user', 'notif_type', 'source_content_type', 'source_object_id')]),
        ),
        migrations.AlterIndexTogether(
            name='notification',
            index_together=set([('user', 'created')]),
        ),
    ]
